In [ ]:
import pandas as pd
df = pd.read_csv("C:/Users/Admin/Downloads/adult.csv")

In [ ]:
print(df)

       age     workclass  fnlwgt     education  educational-num  \
0       25       Private  226802          11th                7
1       38       Private   89814       HS-grad                9
2       28     Local-gov  336951    Assoc-acdm               12
3       44       Private  160323  Some-college               10
4       18             ?  103497  Some-college               10
...    ...           ...     ...           ...              ...
48837   27       Private  257302    Assoc-acdm               12
48838   40       Private  154374       HS-grad                9
48839   58       Private  151910       HS-grad                9
48840   22       Private  201490       HS-grad                9
48841   52  Self-emp-inc  287927       HS-grad                9

           marital-status         occupation relationship   race  gender  \
0           Never-married  Machine-op-inspct    Own-child  Black    Male
1      Married-civ-spouse    Farming-fishing      Husband  White    Male
2      Married-civ-spouse    Protective-serv      Husband  White    Male
3      Married-civ-spouse  Machine-op-inspct      Husband  Black    Male
4           Never-married                  ?    Own-child  White  Female
...                   ...                ...          ...    ...     ...
48837  Married-civ-spouse       Tech-support         Wife  White  Female
48838  Married-civ-spouse  Machine-op-inspct      Husband  White    Male
48839             Widowed       Adm-clerical    Unmarried  White  Female
48840       Never-married       Adm-clerical    Own-child  White    Male
48841  Married-civ-spouse    Exec-managerial         Wife  White  Female

       capital-gain  capital-loss  hours-per-week native-country income
0                 0             0              40  United-States  <=50K
1                 0             0              50  United-States  <=50K
2                 0             0              40  United-States   >50K
3              7688             0              40  United-States   >50K
4                 0             0              30  United-States  <=50K
...             ...           ...             ...            ...    ...
48837             0             0              38  United-States  <=50K
48838             0             0              40  United-States   >50K
48839             0             0              40  United-States  <=50K
48840             0             0              20  United-States  <=50K
48841         15024             0              40  United-States   >50K

[48842 rows x 15 columns]

In [ ]:
df.groupby("gender")["age"].describe()

          count       mean        std   min   25%   50%   75%   max
gender
Female  16192.0  36.927989  14.137423  17.0  25.0  35.0  46.0  90.0
Male    32650.0  39.494395  13.412850  17.0  29.0  38.0  48.0  90.0

In [ ]:
df.agg(['sum', 'min','max'])

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
sum,1887430,PrivatePrivateLocal-govPrivate?Private?Self-em...,9263575662,11thHS-gradAssoc-acdmSome-collegeSome-college1...,492234,Never-marriedMarried-civ-spouseMarried-civ-spo...,Machine-op-inspctFarming-fishingProtective-ser...,Own-childHusbandHusbandHusbandOwn-childNot-in-...,BlackWhiteWhiteBlackWhiteWhiteBlackWhiteWhiteW...,MaleMaleMaleMaleFemaleMaleMaleMaleFemaleMaleMa...,52703821,4273788,1974310,United-StatesUnited-StatesUnited-StatesUnited-...,<=50K<=50K>50K>50K<=50K<=50K<=50K>50K<=50K<=50...
min,17,?,12285,10th,1,Divorced,?,Husband,Amer-Indian-Eskimo,Female,0,0,1,?,<=50K
max,90,Without-pay,1490400,Some-college,16,Widowed,Transport-moving,Wife,White,Male,99999,4356,99,Yugoslavia,>50K

In [ ]:
df.groupby("marital-status")["age"].mean()

marital-status
Divorced                 43.159204
Married-AF-spouse        31.945946
Married-civ-spouse       43.353724
Married-spouse-absent    40.613057
Never-married            28.128064
Separated                39.725490
Widowed                  59.377470
Name: age, dtype: float64

In [ ]:
df.groupby("marital-status")["age"].median()

marital-status
Divorced                 42.0
Married-AF-spouse        30.0
Married-civ-spouse       42.0
Married-spouse-absent    40.0
Never-married            25.0
Separated                39.0
Widowed                  60.0
Name: age, dtype: float64

In [ ]:
df.groupby(["gender","marital-status"])["age"].std()

gender  marital-status
Female  Divorced                 10.794868
        Married-AF-spouse        12.342744
        Married-civ-spouse       11.402805
        Married-spouse-absent    13.019854
        Never-married            10.231671
        Separated                10.757639
        Widowed                  11.657268
Male    Divorced                 10.161659
        Married-AF-spouse         6.336522
        Married-civ-spouse       12.080786
        Married-spouse-absent    12.631023
        Never-married             9.717602
        Separated                10.811704
        Widowed                  14.216489
Name: age, dtype: float64

In [ ]:
df.groupby("income")["age"].mean()

income
<=50K    36.872184
>50K     44.275178
Name: age, dtype: float64

In [ ]:
df.groupby(["income","gender"])["age"].mean()

income  gender
<=50K   Female    36.278999
        Male      37.248548
>50K    Female    42.219333
        Male      44.641863
Name: age, dtype: float64

In [ ]:
df.groupby("marital-status")["marital-status"].count()

marital-status
Divorced                  6633
Married-AF-spouse           37
Married-civ-spouse       22379
Married-spouse-absent      628
Never-married            16117
Separated                 1530
Widowed                   1518
Name: marital-status, dtype: int64

In [ ]:
#Count number of records by category
#The value_counts() method counts the number of records for each category in a column.
df["marital-status"].value_counts()

Married-civ-spouse       22379
Never-married            16117
Divorced                  6633
Separated                 1530
Widowed                   1518
Married-spouse-absent      628
Married-AF-spouse           37
Name: marital-status, dtype: int64

In [ ]:
df["marital-status"].count()

48842